# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action#testing-out-your-action-in-a-workflow
name: Report broken Subreddit sidebar and rule URLs

on:
  schedule:
    - cron: '0 */3 * * *'

# # Every day https://crontab.guru/#45_16_*_*_*
# # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#triggering-a-workflow-with-events
# on:
#   schedule:
#     - cron: '45 16 * * *'

# on: [push]
# on:
#   push:
#     branches:
#       - master

jobs:
  report_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run the node action to validate URLs and create issues
        id: report_job
        uses: r-reactjs/subreddit-rules-url-validator@master
        with:
          subreddit: r/reactjs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
